name = "cavacargo-store"
main = "../utils/api/fetch-product.js"
compatibility_date = "2023-01-01"

[vars]
STRIPE_SECRET_KEY = "sk_test_YOUR_STRIPE_SECRET_KEY"
STRIPE_WEBHOOK_SECRET = "whsec_YOUR_WEBHOOK_SECRET"
TEMU_API_KEY = "YOUR_TEMU_API_KEY"
TEMU_API_URL = "https://api.temu.com/v1/orders"
DOMAIN_URL = "https://yourdomain.com"

[[kv_namespaces]]
binding = "PRODUCTS"
id = "5bec19360e344820a107b828fd675aea"

[[routes]]
pattern = "/api/*"
zone_name = "yourdomain.com"